### ISSUE TITLE
Using doc?

### ISSUE THREAD

**Issue by stefanhuber** [IndefinitivelyTyped/pouchdb#2]
typings i github:IndefinitivelyTyped/pouchdb/index.d.ts#af293b8b2e216f516dc1e2e63b2905614d668593 -SG

no luck with typings version 1.3.2

typings ERR! message Attempted to compile "index" as a global module, but it looks like an external module. You'll need to remove the global option to continue.

typings ERR! cwd /home/stefan/04_js_workspace/beyondit-player-app
typings ERR! system Linux 3.19.0-64-generic
typings ERR! command "/home/stefan/local/bin/node" "/home/stefan/.npm-packages/bin/typings" "i" "github:IndefinitivelyTyped/pouchdb/index.d.ts#af293b8b2e216f516dc1e2e63b2905614d668593" "-SG"
typings ERR! node -v v5.0.0
typings ERR! typings -v 1.3.2

typings ERR! If you need help, you may report this error at:
typings ERR!   https://github.com/typings/typings/issues

**Comment by WorldMaker** [comment]
The issue you are having is the `-SG`. This repo was built for a non-global install (use just `-S`).

**Comment by WorldMaker** [comment]
Also, you could drop the `/index.d.ts` in your path and let typings use the typings.json file to configure.
